apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: canary-demo
  namespace: canary-demo

spec:
  replicas: 3

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: canary-demo

  strategy:
    canary:
      stableService: canary-demo-stable
      canaryService: canary-demo-canary

      steps:
        - setWeight: 10

        - pause:
            duration: 30s

        - setWeight: 25

        - pause:
            duration: 30s

        - setWeight: 50

        - pause:
            duration: 30s

  template:
    metadata:
      labels:
        app: canary-demo

    spec:
      containers:
        - name: canary-demo

          image: 906876220591.dkr.ecr.ap-south-1.amazonaws.com/canary-repo:v1

          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: APP_VERSION
              value: "v2"

            - name: ENVIRONMENT
              value: "production"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20